packages:
  - packages/*

catalog:
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@commitlint/types': ^19.8.1
  '@nestjs/cli': ^11.0.7
  '@nestjs/common': ^11.1.3
  '@nestjs/config': ^4.0.2
  '@nestjs/core': ^11.1.3
  '@nestjs/mapped-types': ^2.1.0
  '@nestjs/platform-fastify': ^11.1.3
  '@nestjs/schematics': ^11.0.5
  '@nestjs/testing': ^11.1.3
  '@nestjs/typeorm': ^11.0.0
  '@rollup/rollup-linux-x64-gnu': ^4.24.3
  '@swc/cli': ^0.7.8
  '@swc/core': ^1.12.11
  '@swc/core-linux-arm64-musl': ^1.7.42
  '@swc/core-linux-x64-gnu': ^1.7.42
  '@swc/core-linux-x64-musl': ^1.7.42
  '@tcgogo/nestjs-trpc-adapter': ^1.0.1
  '@trpc/client': 11.4.3
  '@trpc/server': ^11.4.3
  '@types/express': ^5.0.3
  '@types/fs-extra': ^11.0.4
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.8.7
  '@types/supertest': ^6.0.3
  '@typescript-eslint/eslint-plugin': ^7.18.0
  '@typescript-eslint/parser': ^7.18.0
  '@vitest/coverage-istanbul': 1.3.1
  class-transformer: ^0.5.1
  class-validator: ^0.14.2
  concurrently: ^9.0.1
  copyfiles: ^2.4.1
  eslint: ^8.57.1
  eslint-config-prettier: ^9.0.0
  eslint-plugin-node: ^11.1.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-unicorn: ^56.0.0
  eslint-plugin-vitest: ^0.4.1
  fastify: ^5.4.0
  fs-extra: ^11.2.0
  glob: ^11.0.1
  husky: ^9.1.6
  lint-staged: ^15.2.10
  lodash-es: ^4.17.21
  mysql2: ^3.14.2
  nock: ^13.5.5
  nyc: ^17.1.0
  prettier: ^3.3.3
  reflect-metadata: ^0.2.2
  rimraf: ^6.0.1
  rxjs: ^7.8.2
  source-map-support: ^0.5.21
  supertest: ^7.1.3
  ts-loader: ^9.5.1
  ts-morph: ^25.0.1
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tslib: ^2.8.1
  tsx: ^4.19.2
  type-fest: ^4.41.0
  typeorm: ^0.3.25
  typeorm-naming-strategies: ^4.1.0
  typescript: ^5.6.3
  unplugin-swc: ^1.5.5
  vite: ^6.3.5
  vitest: ^3.2.4
  vitest-mock-extended: ^3.1.0
  yaml: ^2.8.0
  zod: ^4.0.5
