// Generated by ts-to-zod
import { z } from "zod";

export const configSchema = z.object({
    model: z.literal("dashboard"),
    name: z.literal("\u7535\u5546\u7CFB\u7EDF"),
    menu: z.tuple([z.object({
            key: z.literal("product"),
            name: z.literal("\u5546\u54C1"),
            menuType: z.literal("module"),
            moduleType: z.literal("custom"),
            customConfig: z.object({
                path: z.literal("/todo")
            })
        }), z.object({
            key: z.literal("order"),
            name: z.literal("\u8BA2\u5355"),
            menuType: z.literal("module"),
            moduleType: z.literal("custom"),
            customConfig: z.object({
                path: z.literal("/todo")
            })
        }), z.object({
            key: z.literal("client"),
            name: z.literal("\u5BA2\u6237\u7BA1\u7406"),
            menuType: z.literal("module"),
            moduleType: z.literal("custom"),
            customConfig: z.object({
                path: z.literal("/todo")
            })
        })])
});
