DB_CONFIG:
  type: mysql # 数据库链接类型
  host: localhost
  port: 3306
  username: root
  password: '123456'
  database: temp # 后面改成 scid
  retryDelay: 500
  retryAttempts: 10
  synchronize: true # 是否开启同步数据表功能
  autoLoadEntities: true

REDIS_CONFIG:
  host: 127.0.0.1 # redis 链接
  port: 6379 # redis 端口
  db: 0 # redis 数据库

# nest 服务配置
NEST:
  port: 3000

SCID: sca15516911b95f35b

LOG:
  enable: true
  level: debug
