DB_CONFIG:
  type: mysql # 数据库链接类型
  host: 192.168.1.225
  port: 33306
  username: root
  password: iScDb!23465
  database: db_tn_scEFDE4390209585C4 # 后面改成 scid
  retryDelay: 500
  retryAttempts: 10
  synchronize: false # 是否开启同步数据表功能
  autoLoadEntities: true

REDIS_CONFIG:
  password: iSc!23465Test83
  host: 192.168.1.203 # redis 链接
  port: 6379 # redis 端口
  db: 3 # redis 数据库

# nest 服务配置
NEST:
  port: 3000

SCID: scEFDE4390209585C4

LOG:
  enable: false
  level: info
