import "./common-AJXMMmZt.js";
import "./defineProperty-DOiqJb-o.js";
import "./asyncToGenerator-CDlr4A8U.js";
import "./decorate-X8-ckSX6.js";
import "./app-router.host-CRteAOv-.js";
import "./procedure.factory-BVIy_yls.js";
import "./trpc.constants-bTuZEOOy.js";
import "./node-http-ZvZKxPic-xWxFTMZn.js";
import "./factory.interface-1IZgsKBO.js";
import "./trpc.enum-XZGct68f.js";
import "./decorateMetadata-BmFM2rdr.js";
import "./router.factory-BOgtMUHn.js";
import "./trpc.factory-BntEt_3S.js";
import "./fastify.driver-D__pY79n.js";
import "./express.driver-Crc-0hjX.js";
import "./drivers-DYhUCXca.js";
import "./trpc.driver-C7vGo1xo.js";
import "./file.scanner-DjuJxM_C.js";
import "./ts-morph.util-5vn0uEp8.js";
import "./imports.scanner-m3j-zqOP.js";
import "./static.generator-FNFHztAl.js";
import "./generator.constants-BHzRvyZp.js";
import "./procedure.generator-BS8c8w2r.js";
import "./decorator.generator-D0om8ofS.js";
import "./router.generator-g-vnolCV.js";
import "./middleware.generator-BEnXpCqH.js";
import "./context.generator-DKcrJxMc.js";
import "./middleware.factory-CF9uL2dJ.js";
import "./trpc.generator-BZIXkgz1.js";
import "./factory.module-BmTzhaV0.js";
import "./scanner.module-BvKWasal.js";
import "./generator.module-ul8O5jzm.js";
import { TRPCModule } from "./trpc.module-fyHvT9LO.js";

export { TRPCModule };