import type { MenuItem } from './type'
// Generated by ts-to-zod
import { z } from 'zod'

export const menuMetaSchema = z.object({
  title: z.string(),
  icon: z.string().optional(),
})

export const menuItemSchema: z.ZodSchema<MenuItem> = z.lazy(() => z.object({
  path: z.string().optional(),
  component: z.string().optional(),
  name: z.string().optional(),
  meta: menuMetaSchema.optional(),
  children: z.array(menuItemSchema).optional(),
}))

export const modelSchema = z.object({
  title: z.string(),
  model: z.string(),
  menu: z.array(menuItemSchema),
})

export default modelSchema
